version: "3.9"
services:
  db:
    container_name: next-llm-ctf-postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: next-llm-ctf
  
  app:
    depends_on:
      - db
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_AUTHENTIK_ID: ${AUTH_AUTHENTIK_ID}
      AUTH_AUTHENTIK_SECRET: ${AUTH_AUTHENTIK_SECRET}
      AUTH_AUTHENTIK_ISSUER: ${AUTH_AUTHENTIK_ISSUER}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
